name = "HydrologyPlanetesimals"
uuid = "0f588840-2752-41b6-aea8-a336b7e3b19f"
authors = ["Beat Hubmann"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
ArgParse = "1"
DocStringExtensions = "0.8"
DocumenterTools = "0.1"
ExtendableSparse = "0.6"
JLD2 = "0.4"
Parameters = "0.12"
ProgressMeter = "1"
StaticArrays = "1"
TimerOutputs = "0.5"
UnicodePlots = "2"
julia = "1.7.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
